import { INodeProperties } from 'n8n-workflow';

export const itemOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['item'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create an item',
				description: 'Catalog item. Both name AND description are required by Morning.',
				routing: { request: { method: 'POST', url: '/items' } },
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get an item',
				routing: { request: { method: 'GET', url: '=/items/{{ $parameter["itemId"] }}' } },
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update an item',
				routing: { request: { method: 'PUT', url: '=/items/{{ $parameter["itemId"] }}' } },
			},
			{
				name: 'Search',
				value: 'search',
				action: 'Search items',
				routing: { request: { method: 'POST', url: '/items/search' } },
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete an item',
				description: 'Allowed even when referenced by historical documents — docs keep their snapshot.',
				routing: { request: { method: 'DELETE', url: '=/items/{{ $parameter["itemId"] }}' } },
			},
		],
		default: 'create',
	},
];

export const itemFields: INodeProperties[] = [
	{
		displayName: 'Item ID',
		name: 'itemId',
		type: 'string',
		required: true,
		default: '',
		description: 'The UUID of the catalog item to act on',
		displayOptions: { show: { resource: ['item'], operation: ['get', 'update', 'delete'] } },
	},
	{
		displayName: 'Name',
		name: 'itemName',
		type: 'string',
		default: '',
		required: true,
		description: "The catalog item's name (separate from the required Description field)",
		displayOptions: { show: { resource: ['item'], operation: ['create', 'update'] } },
		routing: { send: { type: 'body', property: 'name' } },
	},
	{
		displayName: 'Description',
		name: 'description',
		type: 'string',
		default: '',
		required: true,
		description: 'REQUIRED by Morning (separate field from name)',
		displayOptions: { show: { resource: ['item'], operation: ['create', 'update'] } },
		routing: { send: { type: 'body', property: 'description' } },
	},
	{
		displayName: 'Catalog Number',
		name: 'catalogNumber',
		type: 'string',
		default: '',
		description: 'Optional SKU / catalog number identifying the item',
		displayOptions: { show: { resource: ['item'], operation: ['create', 'update'] } },
		routing: {
			send: { type: 'body', property: 'catalogNumber', value: '={{ $value || undefined }}' },
		},
	},
	{
		displayName: 'Price',
		name: 'price',
		type: 'number',
		default: 0,
		description: 'Unit price of the item, interpreted per the VAT Type below',
		displayOptions: { show: { resource: ['item'], operation: ['create', 'update'] } },
		routing: { send: { type: 'body', property: 'price' } },
	},
	{
		displayName: 'Currency',
		name: 'currency',
		type: 'string',
		default: 'ILS',
		description: 'ISO 4217 currency code for the price (e.g. "ILS", "USD", "EUR")',
		displayOptions: { show: { resource: ['item'], operation: ['create', 'update'] } },
		routing: { send: { type: 'body', property: 'currency' } },
	},
	{
		displayName: 'VAT Type',
		name: 'vatType',
		type: 'options',
		options: [
			{ name: '0 — Price BEFORE VAT', value: 0 },
			{ name: '1 — VAT INCLUDED', value: 1 },
			{ name: '2 — VAT exempt', value: 2 },
		],
		default: 1,
		description: 'How the Price relates to VAT: 0 = before VAT, 1 = VAT included, 2 = exempt',
		displayOptions: { show: { resource: ['item'], operation: ['create', 'update'] } },
		routing: { send: { type: 'body', property: 'vatType' } },
	},
	{
		displayName: 'Search Term',
		name: 'searchTerm',
		type: 'string',
		default: '',
		description: 'Free-text term to search items by name',
		displayOptions: { show: { resource: ['item'], operation: ['search'] } },
		routing: {
			send: { type: 'body', property: 'name', value: '={{ $value || undefined }}' },
		},
	},
	{
		displayName: 'Page',
		name: 'page',
		type: 'number',
		default: 1,
		description: 'Page number of search results to return (1-based)',
		displayOptions: { show: { resource: ['item'], operation: ['search'] } },
		routing: { send: { type: 'body', property: 'page' } },
	},
	{
		displayName: 'Page Size',
		name: 'pageSize',
		type: 'number',
		default: 50,
		typeOptions: { minValue: 1, maxValue: 100 },
		description: 'Number of results per page (1-100)',
		displayOptions: { show: { resource: ['item'], operation: ['search'] } },
		routing: { send: { type: 'body', property: 'pageSize' } },
	},
];
